v2apiURLList:
#  - url: http://intra.val.co.jp:8080/expwww2/expcgi.exe
#    comment: V3(Jenkins)
  - url: http://compatible.ekispert.com/expwww2/exp.cgi
    comment: 本番環境
  - url: http://intra.val.co.jp/expwww2/expcgi.exe
    comment: V2最新版(Windows)

