v2apiURLList:
#  - url: http://intra.val.co.jp:8080/expwww2/expcgi.exe
#    comment: V3(Jenkins)
  - url: http://172.17.11.70:4747/expwww2/exp.cgi
    comment: 互換IF(納谷の開発マシン、通常稼働してないので使いたい場合はハングアウト)
  - url: http://intra.val.co.jp/expwww2/expcgi.exe
    comment: V2最新版(Windows)

