v2apiURLList:
  - url: http://intra.val.co.jp:8080/expwww2/expcgi.exe
    comment: V3(Jenkins)
  - url: http://intra.val.co.jp/expwww2/expcgi.exe
    comment: V2最新版(Windows)
  - url: http://172.17.11.70/expwww2/exp.cgi
    comment: naya_dev
